# Generated by Django 5.2 on 2025-04-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_seqnumd'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packaged',
            table='shipments',
        ),
    ]
